"""Build data.js from d3-celestial data (npm pack d3-celestial; pass path to its data dir)."""
import json, sys
from opencc import OpenCC

src = sys.argv[1].rstrip('/') + '/'
out = sys.argv[2]
cc = OpenCC('s2twp')
load = lambda f: json.load(open(src + f, encoding='utf-8'))

def ra(x):  # d3-celestial lon is [-180,180]; convert to RA degrees [0,360)
    return round(x % 360, 2)

# Stars to mag 6: flat array [ra, dec, mag, bv, ...]
stars = []
hip_index = {}
for f in sorted(load('stars.6.json')['features'], key=lambda f: f['properties']['mag']):
    p = f['properties']; lon, lat = f['geometry']['coordinates']
    try: bv = round(float(p['bv']), 1)
    except (ValueError, TypeError): bv = 0.6
    hip_index[str(f['id'])] = len(stars) // 4
    stars += [ra(lon), round(lat, 2), round(p['mag'], 2), bv]

# Named bright stars (English proper name -> Traditional Chinese common name)
ZH = {
 'Sirius':'天狼星','Canopus':'老人星','Arcturus':'大角星','Vega':'織女星','Capella':'五車二',
 'Rigel':'參宿七','Procyon':'南河三','Betelgeuse':'參宿四','Achernar':'水委一','Hadar':'馬腹一',
 'Altair':'牛郎星','Acrux':'十字架二','Aldebaran':'畢宿五','Antares':'心宿二','Spica':'角宿一',
 'Pollux':'北河三','Fomalhaut':'北落師門','Deneb':'天津四','Mimosa':'十字架三','Regulus':'軒轅十四',
 'Adhara':'弧矢七','Castor':'北河二','Shaula':'尾宿八','Gacrux':'十字架一','Bellatrix':'參宿五',
 'Elnath':'五車五','Miaplacidus':'南船五','Alnilam':'參宿二','Alnair':'鶴一','Alnitak':'參宿一',
 'Alioth':'玉衡','Dubhe':'天樞','Mirfak':'天船三','Wezen':'弧矢一','Sargas':'尾宿五',
 'Kaus Australis':'箕宿三','Avior':'海石一','Alkaid':'搖光','Menkalinan':'五車三','Atria':'三角形三',
 'Alhena':'井宿三','Peacock':'孔雀十一','Polaris':'北極星','Mirzam':'軍市一','Alphard':'星宿一',
 'Hamal':'婁宿三','Algieba':'軒轅十二','Diphda':'土司空','Nunki':'斗宿四','Menkent':'庫樓三',
 'Mirach':'奎宿九','Alpheratz':'壁宿二','Rasalhague':'候','Kochab':'帝','Saiph':'參宿六',
 'Denebola':'五帝座一','Algol':'大陵五','Shedar':'王良四','Caph':'王良一','Mizar':'開陽',
 'Merak':'天璇','Phecda':'天璣','Megrez':'天權','Enif':'危宿三','Markab':'室宿一','Scheat':'室宿二',
 'Algenib':'壁宿一','Sadr':'天津一','Albireo':'輦道增七','Eltanin':'天棓四','Alderamin':'天鉤五',
 'Mintaka':'參宿三','Alcyone':'昴宿六','Zubenelgenubi':'氐宿一','Zubeneschamali':'氐宿四',
 'Almach':'天大將軍一','Menkar':'天囷一','Mira':'蒭藁增二','Sadalsuud':'虛宿一','Sadalmelik':'危宿一',
 'Dschubba':'房宿三','Vindemiatrix':'太微左垣四','Cor Caroli':'常陳一','Alphecca':'貫索四',
 'Unukalhai':'天市右垣七','Rasalgethi':'帝座','Kornephoros':'河中','Tarazed':'河鼓三','Ruchbah':'閣道三',
 'Izar':'梗河一','Muphrid':'右攝提一','Deneb Algedi':'壘壁陣四','Nashira':'壘壁陣三',
}
best = {}
for hip, n in load('starnames.json').items():
    en = n.get('name')
    if en in ZH and hip in hip_index and (en not in best or hip_index[hip] < best[en][0]):
        best[en] = [hip_index[hip], ZH[en], en, n.get('c', '')]
names = sorted(best.values())
missing = set(ZH) - {x[2] for x in names}
if missing: print('missing star names:', missing, file=sys.stderr)

# Constellations: names, label position, line segments
info = {f['id']: f for f in load('constellations.json')['features']}
cons = []
for f in load('constellations.lines.json')['features']:
    i = info[f['id']]; p = i['properties']; lon, lat = i['geometry']['coordinates']
    lines = [[c for pt in ln for c in (ra(pt[0]), round(pt[1], 2))] for ln in f['geometry']['coordinates']]
    cons.append({'id': f['id'], 'zh': cc.convert(p['zh']), 'en': p['name'], 'rank': int(p['rank']),
                 'c': [ra(lon), round(lat, 1)], 'l': lines})

# Messier objects (bright subset) + a few naked-eye extras
TYPE = {'gc':'球狀星團','oc':'疏散星團','pn':'行星狀星雲','snr':'超新星殘骸','en':'發射星雲','bn':'星雲',
        'dn':'暗星雲','rn':'反射星雲','sfr':'恆星形成區','gg':'星系','g':'星系','s':'螺旋星系','sd':'星系',
        's0':'透鏡狀星系','e':'橢圓星系','i':'不規則星系','*':'恆星'}
ALT = {'M31':'仙女座大星系','M45':'昴宿星團','M42':'獵戶座大星雲','M44':'蜂巢星團','M8':'礁湖星雲',
       'M13':'武仙座球狀星團','M22':'人馬座球狀星團','M7':'托勒密星團','M6':'蝴蝶星團','M33':'三角座星系',
       'M57':'環狀星雲','M27':'啞鈴星雲','M17':'天鵝星雲','M20':'三裂星雲','M1':'蟹狀星雲','M11':'野鴨星團',
       'M16':'鷹星雲','M51':'渦狀星系','M81':'波德星系','M104':'草帽星系','M24':'人馬座恆星雲'}
dsos = []
for f in load('messier.json')['features']:
    p = f['properties']; lon, lat = f['geometry']['coordinates']
    if p['mag'] <= 7.5 or f['id'] in ALT:
        dsos.append([ra(lon), round(lat, 2), f['id'], ALT.get(f['id'], ''), TYPE.get(p['type'], ''), p['mag']])

data = {'stars': stars, 'names': names, 'cons': cons, 'dsos': dsos}
with open(out, 'w', encoding='utf-8') as fh:
    fh.write('// Generated by tools/build_data.py from d3-celestial (BSD-3-Clause) data.\n')
    fh.write('window.SKY=' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')
print('stars', len(stars)//4, 'names', len(names), 'cons', len(cons), 'dsos', len(dsos))
